### ISSUE TITLE
Homepage layout is off

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/geonode#51]
It is now like this ![image](https://user-images.githubusercontent.com/1036189/27327809-15051eba-55b0-11e7-88a1-b9ebfe3d4f6e.png)

And it used to be like that:
![image](https://user-images.githubusercontent.com/1036189/27327835-2b693754-55b0-11e7-914a-96a6271a99ac.png)

**Comment by vdeparday** [comment]
I meant the margin below Open Data to further your understanding. I think we can just delete the Welcome to get back in the previous state.

**Comment by stufraser1** [comment]
@Vampouille can this (simple) change be made quickly so we can close this issue?

**Comment by Vampouille** [comment]
Done with: https://github.com/Vampouille/geonode/commit/ac3ab00074e3a22a977b8981a5f47dfbe191d257 and build in docker image camptocamp/geonode_django:20171019113544 and camptocamp/geonode_django:2.7-gfdrr-ac3ab00-psycopg2.7
I just install it on int instance, run a `python manage.py collectstatic` to deploy static files and run `python manage.py migrate` to migrate database.

**Comment by Vampouille** [comment]
Also applied on prod instance

**Comment by vdeparday** [comment]
I still see the same layout issue: 
![image](https://user-images.githubusercontent.com/1036189/31795387-9997240a-b4f3-11e7-98a9-cd8cb67e4d31.png)

**Comment by stufraser1** [comment]
@vdeparday I can't replicate this - tested on Firefox and Chrome on wide and small screen
Can you check and close if you see its resolved? Thanks
This is what I see in all cases
![image](https://user-images.githubusercontent.com/12515042/31995192-5767c35a-b97b-11e7-959e-9cd7283fb342.png)

**Comment by vdeparday** [comment]
Working now, may have been some caching issues although I forced refreshed.
